// This file was automatically generated by 'Kmisc::registerFunctions()'

#include <R.h>
#include <Rinternals.h>

#include <R_ext/Rdynload.h>

SEXP GOpro_fisher_test(SEXP aSEXP, SEXP bSEXP, SEXP cSEXP, SEXP dSEXP);
// [[Rcpp::export]]double fisher_test(double a, double b, double c, double d);

R_CallMethodDef callMethods[]  = {
  {"GOpro_fisher_test", (DL_FUNC) &GOpro_fisher_test, 4},
  {NULL, NULL, 0}
};

void R_init_GOpro(DllInfo *info) {
  R_registerRoutines(info, NULL, callMethods, NULL, NULL);
  R_useDynamicSymbols(info, FALSE);
}

